name: CI-CD

on:
  push: 
    branches: ["main"]
  workflow_dispatch:

jobs:
  ci: 
    runs-on: ubuntu-latest
    steps:
      - name: dokerhub
        run: echo "dockerhub"
  cd: 
    runs-on: ubuntu-latest
    steps:
      - name: aws
        run: echo "aws"
